### ISSUE TITLE
Linux: Unending scanning and `sharp.lua:133: assertion failed!`

### ISSUE THREAD

**Issue by WaffleLapkin** [EverestAPI/Olympus#21]
I'm ~~the 12-th linux user~~ trying to use `olympus` on Arch Linux with steam celeste installation, but it doesn't seem to work. When I run it, it just stucks in the "Scanning..." state. Using "Manually select Celeste.exe" doesn't help either. Here are the logs:

<details><summary>stdout log</summary>
<p>

```
; ./olympus
pre-initializing
cwd:	/home/waffle/Downloads/dist
src:	/home/waffle/Downloads/dist
storageDir:	/home/waffle/.config/Olympus
pre-initialized
love2d version	11.3.0.Mysterious Mysteries
SDL2 version	2.0.10
Olympus version	21.07.23.02-azure-2253-954da
[sharp init]	starting thread
[sharp init]	starting subprocess	/home/waffle/Downloads/dist/sharp/Olympus.Sharp.bin.x86_64	8400	nil
[sharp init]	logging to	/home/waffle/.config/Olympus/log-sharp.txt
[sharp init]	reading init
[sharpthread error]	sharp.lua:133: assertion failed!
stack traceback:
	[C]: in function 'assert'
	sharp.lua:133: in function <sharp.lua:28>
	[C]: in function 'xpcall'
	sharp.lua:28: in function 'fun'
	string:33: in function <string:32>
	[C]: in function 'xpcall'
	string:31: in main chunk
[finder]	steam root	/home/waffle/.local/share/Steam	<same>
[finder]	steam common	/home/waffle/.local/share/Steam/steamapps/common
[finder]	steam common	/home/waffle/steam/steamapps/common
[finder]	steam additional library	/home/waffle/steam/steamapps/common
[finder]	steam install	/home/waffle/.local/share/Steam/steamapps/common/Celeste
[finder]	steam root	/home/waffle/.local/share/Steam	<same>
[finder]	itch db	/home/waffle/.config/itch/db/butler.db	false
[finder]	lutris db	/home/waffle/.local/share/lutris/pga.db	<same>
[finder]	lutris root	/home/waffle/.config/lutris	<same>
[finder]	legendary root	/home/waffle/.config/legendary	false
```

</p>
</details>

<details><summary>`log-sharp.txt`</summary>
<p>

```
/home/waffle/Downloads/dist
FATAL ERROR
System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system. ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section <startup> (/home/waffle/Downloads/dist/sharp/Olympus.Sharp.exe.config line 3)
  at System.Configuration.ConfigInfo.ThrowException (System.String text, System.Xml.XmlReader reader) [0x00007] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.SectionGroupInfo.ReadContent (System.Xml.XmlReader reader, System.Configuration.Configuration config, System.Boolean overrideAllowed, System.Boolean root) [0x00135] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.SectionGroupInfo.ReadRootData (System.Xml.XmlReader reader, System.Configuration.Configuration config, System.Boolean overrideAllowed) [0x00007] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.ReadConfigFile (System.Xml.XmlReader reader, System.String fileName) [0x000ce] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.Load () [0x00043] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.Init (System.Configuration.Internal.IConfigSystem system, System.String configPath, System.Configuration.Configuration parent) [0x0005d] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration..ctor (System.Configuration.InternalConfigurationSystem system, System.String locationSubPath) [0x00056] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.InternalConfigurationFactory.Create (System.Type typeConfigHost, System.Object[] hostInitConfigurationParams) [0x0000d] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ConfigurationManager.OpenExeConfigurationInternal (System.Configuration.ConfigurationUserLevel userLevel, System.Reflection.Assembly calling_assembly, System.String exePath) [0x000ef] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ClientConfigurationSystem.get_Configuration () [0x0000e] in <1e6a1e890ba741b38804396a1899ecf8>:0
   --- End of inner exception stack trace ---
  at System.Configuration.ClientConfigurationSystem.get_Configuration () [0x0002a] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection (System.String configKey) [0x00000] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ConfigurationManager.GetSection (System.String sectionName) [0x00005] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Net.ServicePointManager..cctor () [0x0003c] in <32fc020d7373456995b3d44fa885e01a>:0
   --- End of inner exception stack trace ---
  at Olympus.Program.Main (System.String[] args) [0x0013c] in <ed9d8567279b4b6c8462b4649eed87fc>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system. ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section <startup> (/home/waffle/Downloads/dist/sharp/Olympus.Sharp.exe.config line 3)
  at System.Configuration.ConfigInfo.ThrowException (System.String text, System.Xml.XmlReader reader) [0x00007] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.SectionGroupInfo.ReadContent (System.Xml.XmlReader reader, System.Configuration.Configuration config, System.Boolean overrideAllowed, System.Boolean root) [0x00135] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.SectionGroupInfo.ReadRootData (System.Xml.XmlReader reader, System.Configuration.Configuration config, System.Boolean overrideAllowed) [0x00007] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.ReadConfigFile (System.Xml.XmlReader reader, System.String fileName) [0x000ce] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.Load () [0x00043] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration.Init (System.Configuration.Internal.IConfigSystem system, System.String configPath, System.Configuration.Configuration parent) [0x0005d] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.Configuration..ctor (System.Configuration.InternalConfigurationSystem system, System.String locationSubPath) [0x00056] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.InternalConfigurationFactory.Create (System.Type typeConfigHost, System.Object[] hostInitConfigurationParams) [0x0000d] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ConfigurationManager.OpenExeConfigurationInternal (System.Configuration.ConfigurationUserLevel userLevel, System.Reflection.Assembly calling_assembly, System.String exePath) [0x000ef] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ClientConfigurationSystem.get_Configuration () [0x0000e] in <1e6a1e890ba741b38804396a1899ecf8>:0
   --- End of inner exception stack trace ---
  at System.Configuration.ClientConfigurationSystem.get_Configuration () [0x0002a] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection (System.String configKey) [0x00000] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Configuration.ConfigurationManager.GetSection (System.String sectionName) [0x00005] in <1e6a1e890ba741b38804396a1899ecf8>:0
  at System.Net.ServicePointManager..cctor () [0x0003c] in <32fc020d7373456995b3d44fa885e01a>:0
   --- End of inner exception stack trace ---
  at Olympus.Program.Main (System.String[] args) [0x0013c] in <ed9d8567279b4b6c8462b4649eed87fc>:0
```

</p>
</details>

**Comment by metamuffin** [comment]
This fix (at least on my machine) fixes, the original issue, but creates a new one, where at downloading mods other errors occurr.
```
[sharp] Task (installMod)(thread#96>sharp.lua:431<scenes/installer.lua:344)#1 failed: System.NotSupportedException: The URI prefix is not recognized.
```
This looks alot like if there were features, only enabled through specifing the runtime version.

**Comment by 0x0ade** [comment]
That's because the original fix was not the right solution for this. It's
very likely that you've got a system installation of Mono that is
conflicting with MonoKickstart. This issue was resolved properly on the
Celeste Discord server multiple times (search for "mono version conflicts"
as a starting point for the latest attempt). I didn't get to this issue yet
though and I'll head out to work soon, just saw this pop up in my email
inbox. It doesn't help that I'm currently rewriting Olympus from scratch
anyway.

metamuffin ***@***.***> schrieb am Di., 2. Nov. 2021, 08:01:

**Comment by metamuffin** [comment]
Thanks a lot. It seems to work properly again.
Would it be useful to include an option to run olympus with the system installation of mono for the 13 other GNU+Linux users?

**Comment by WaffleLapkin** [comment]
For the record: yes, removal of `<startup>` only changed the issue for me and did not actually solve it (I added it back in the end). The actual solution was [proposed](https://discord.com/channels/403698615446536203/514006912115802113/896063932287041627) by `@jade` on the Celeste discord. rl;dr it's just a hacky way to use system mono installation instead of MonoKickstart.

**Comment by Enkrypt512** [comment]
necrombumping this,this issue seems to be fixed :D
